FROM ubuntu:20.04
RUN apt-get update && apt-get install -y python3.8 python3.8-pip
COPY requirements.txt .
RUN if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
COPY . .
CMD ["python3.8", "/app.py"]